# BoardConfig.mk for Panasonic Eluga Ray X (MT6737M)

TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a7
TARGET_BOARD_PLATFORM := mt6737m
TARGET_NO_BOOTLOADER := true
BOARD_HAS_NO_REAL_SDCARD := true
BOARD_USE_CUSTOM_RECOVERY_FONT := "roboto_15x24.h"

TARGET_PREBUILT_KERNEL := device/panasonic/elugarayx/zImage
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,32N2
BOARD_KERNEL_BASE := 0x40078000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_MKBOOTIMG_ARGS := --base 0x40078000 --pagesize 2048

TARGET_RECOVERY_FSTAB := device/panasonic/elugarayx/recovery.fstab
BOARD_HAS_MTK_HARDWARE := true
BOARD_SUPPRESS_SECURE_ERASE := true

TW_THEME := portrait_hdpi
TW_INCLUDE_CRYPTO := false
TW_USE_MODEL_HARDWARE_ID_FOR_DEVICE_ID := true
TW_EXCLUDE_TWRPAPP := true
TW_INCLUDE_REPACKTOOLS := true