name: Build TWRP for Panasonic Eluga Ray X

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt update
          sudo apt install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib           libc6-dev-i386 libncurses-dev lib32ncurses-dev x11proto-core-dev libx11-dev lib32z-dev           ccache libgl1-mesa-dev libxml2-utils xsltproc unzip bc python3 liblz4-tool

      - name: Install repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo 'export PATH=~/bin:$PATH' >> $GITHUB_ENV

      - name: Initialize repo and sync sources
        run: |
          mkdir -p ~/twrp
          cd ~/twrp
          ~/bin/repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-11
          ~/bin/repo sync -j4
          git clone https://github.com/bobthebuilder-69/twrp_eluga_ray_x.git device/panasonic/elugarayx

      - name: Build TWRP
        run: |
          cd ~/twrp
          source build/envsetup.sh
          lunch omni_elugarayx-eng
          mka recoveryimage