name: Build TWRP for Panasonic Eluga Ray X (with repo sync)

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your device tree
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y bc bison build-essential curl flex g++-multilib gcc-multilib \
          git gnupg gperf libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc \
          zip zlib1g-dev liblz4-tool imagemagick libncurses-dev libssl-dev \
          python3 unzip ccache openjdk-8-jdk

      - name: Install repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo 'export PATH=~/bin:$PATH' >> $GITHUB_ENV

      - name: Initialize TWRP repo
        run: |
          mkdir -p ~/twrp
          cd ~/twrp
          ~/bin/repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-11 --depth=1

      - name: Sync TWRP repo
        run: |
          cd ~/twrp
          ~/bin/repo sync -j2 --no-tags --no-clone-bundle

      - name: Copy device tree into TWRP source
        run: |
          mkdir -p ~/twrp/device/panasonic/elugarayx
          cp -r $GITHUB_WORKSPACE/device/panasonic/elugarayx/* ~/twrp/device/panasonic/elugarayx/

      - name: Build TWRP
        run: |
          cd ~/twrp
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          lunch omni_elugarayx-eng
          mka recoveryimage -j2
