name: Build TWRP for Panasonic Eluga Ray X (GitHub-safe)

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your device tree
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y bc bison build-essential curl flex g++-multilib gcc-multilib \
          git gnupg gperf libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc \
          zip zlib1g-dev liblz4-tool imagemagick libncurses-dev libssl-dev \
          python3 unzip ccache openjdk-8-jdk

      - name: Create TWRP folder structure
        run: mkdir -p ~/twrp/device/panasonic/elugarayx

      - name: Copy device tree
        run: cp -r $GITHUB_WORKSPACE/device/panasonic/elugarayx/* ~/twrp/device/panasonic/elugarayx/

      - name: Checkout TWRP source (build)
        uses: actions/checkout@v3
        with:
          repository: minimal-manifest-twrp/android_build
          path: ~/twrp/build

      - name: Checkout TWRP recovery
        uses: actions/checkout@v3
        with:
          repository: minimal-manifest-twrp/android_bootable_recovery
          path: ~/twrp/bootable/recovery

      - name: Checkout core
        uses: actions/checkout@v3
        with:
          repository: minimal-manifest-twrp/android_system_core
          path: ~/twrp/system/core

      - name: Checkout sepolicy
        uses: actions/checkout@v3
        with:
          repository: minimal-manifest-twrp/android_system_sepolicy
          path: ~/twrp/system/sepolicy

      - name: Checkout extras
        run: |
          cd ~/twrp
          git clone --depth=1 https://github.com/minimal-manifest-twrp/android_external_busybox.git external/busybox
          git clone --depth=1 https://github.com/minimal-manifest-twrp/android_external_toybox.git external/toybox
          git clone --depth=1 https://github.com/minimal-manifest-twrp/android_external_e2fsprogs.git external/e2fsprogs
          git clone --depth=1 https://github.com/minimal-manifest-twrp/android_external_libtar.git external/libtar
          git clone --depth=1 https://github.com/minimal-manifest-twrp/android_external_f2fs-tools.git external/f2fs-tools

      - name: Build TWRP
        run: |
          cd ~/twrp
          source build/envsetup.sh || true
          export ALLOW_MISSING_DEPENDENCIES=true
          lunch omni_elugarayx-eng
          mka recoveryimage -j2
