name: Minimal TWRP Build for Panasonic Eluga Ray X

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your device tree
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y bc bison build-essential curl flex g++-multilib gcc-multilib \
          git gnupg gperf libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc \
          zip zlib1g-dev liblz4-tool imagemagick libncurses-dev libssl-dev libtinfo5 \
          python3 unzip ccache openjdk-8-jdk

      - name: Clone minimal TWRP sources
        run: |
          git config --global user.name "builder"
          git config --global user.email "builder@example.com"
          mkdir ~/twrp && cd ~/twrp
          git clone https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-11 .repo/manifests
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-11 --depth=1
          repo sync -c --no-tags --no-clone-bundle -j2

      - name: Copy your device tree
        run: |
          mkdir -p ~/twrp/device/panasonic/elugarayx
          cp -r $GITHUB_WORKSPACE/device/panasonic/elugarayx/* ~/twrp/device/panasonic/elugarayx/

      - name: Build TWRP
        run: |
          cd ~/twrp
          source build/envsetup.sh
          lunch omni_elugarayx-eng
          mka recoveryimage
          
